version: "2"
services:
  # thesis-node-server:
  #   build: ../Server
  #   restart: always
  #   container_name: "thesis-node-server"
  #   ports:
  #       - "8080:8080"
  #   links:
  #       - mongo
  #   depends_on:
  #       - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ../database/thesis:/data/db
    ports:
      - "27017:27017"
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo

